apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aniverse-web
spec:
  ingressClassName: nginx
  rules:
    - host: aniverse.lab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aniverse-web
                port:
                  number: 80
