# Generated by Django 6.0.6 on 2026-07-10 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('anime_title', models.CharField(max_length=100, verbose_name='작품명(태그)')),
                ('category', models.CharField(choices=[('acrylic', '아크릴 스탠드/키링'), ('badge', '캔뱃지/핀버튼'), ('figure', '피규어/넨도로이드'), ('plush', '인형/누이구루미'), ('paper', '지류(파샤/포카/특전)'), ('etc', '기타')], default='etc', max_length=20, verbose_name='굿즈 종류')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('status', models.CharField(choices=[('sale', '판매중'), ('reserved', '예약중'), ('sold', '판매완료')], default='sale', max_length=10, verbose_name='거래 상태')),
                ('shipping_methods', models.CharField(help_text='ex: GS반택, 준등기', max_length=200, verbose_name='배송 방법')),
                ('image', models.CharField(blank=True, max_length=500, null=True, verbose_name='굿즈 사진 URL')),
                ('description', models.TextField(verbose_name='상세 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='판매자')),
            ],
        ),
    ]
