# Generated by Django 6.0.6 on 2026-07-13 06:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='buyer_last_viewed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='구매자 최종 확인 시각'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatroom',
            name='seller_last_viewed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='판매자 최종 확인 시각'),
            preserve_default=False,
        ),
    ]
