# Generated by Django 6.0.6 on 2026-07-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0004_chatroom_buyer_last_viewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='buyer_left',
            field=models.BooleanField(default=False, verbose_name='구매자 나감 여부'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='seller_left',
            field=models.BooleanField(default=False, verbose_name='판매자 나감 여부'),
        ),
    ]
