# Generated by Django 6.0.6 on 2026-07-14 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0005_chatroom_buyer_left_chatroom_seller_left'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='찜한 시각')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='deal.goods', verbose_name='찜한 굿즈')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'goods')},
            },
        ),
    ]
