# Generated by Django 6.0.6 on 2026-07-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
