# Generated by Django 6.0.6 on 2026-07-16 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0007_goods_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fraud', '사기 의심'), ('fake', '허위매물/과장광고'), ('prohibited', '거래 불가 품목'), ('duplicate', '중복/도배 등록'), ('etc', '기타')], max_length=20, verbose_name='신고 사유')),
                ('detail', models.TextField(blank=True, verbose_name='상세 내용')),
                ('status', models.CharField(choices=[('pending', '대기'), ('resolved', '처리완료'), ('rejected', '반려')], default='pending', max_length=10, verbose_name='처리 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신고일')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='deal.goods', verbose_name='신고 대상 굿즈')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_reports', to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('reporter', 'goods')},
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fraud', '사기 피해'), ('abusive', '비매너/욕설'), ('noshow', '노쇼/일방적 거래 취소'), ('etc', '기타')], max_length=20, verbose_name='신고 사유')),
                ('detail', models.TextField(blank=True, verbose_name='상세 내용')),
                ('status', models.CharField(choices=[('pending', '대기'), ('resolved', '처리완료'), ('rejected', '반려')], default='pending', max_length=10, verbose_name='처리 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신고일')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL, verbose_name='신고 대상 유저')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_user_reports', to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('reporter', 'reported_user')},
            },
        ),
    ]
