version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app # ubuntu 홈 디렉터리로 지정

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu # 👈 ec2-user -> ubuntu로 변경

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu # 👈 ec2-user -> ubuntu로 변경

  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ubuntu # 👈 ec2-user -> ubuntu로 변경
