version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing only necessary system dependencies for mysqlclient..."
      - yum install -y pkgconfig mysql-devel gcc python3-devel
      - echo "Creating virtual environment..."
      - python3.11 -m venv venv
      - echo "Installing dependencies..."
      - venv/bin/pip install --upgrade pip
      - venv/bin/pip install -r requirements.txt
  build:
    commands:
      - echo "Running collectstatic..."
      - venv/bin/python manage.py collectstatic --noinput

artifacts:
  files:
    - '**/*'
