version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Creating virtual environment..."
      - python3 -m venv venv
      - . venv/bin/activate
      - echo "Upgrading pip and installing dependencies inside venv..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running static files collection inside venv..."
      - . venv/bin/activate
      - python manage.py collectstatic --noinput
artifacts:
  files:
    - '**/*'
