# Generated by Django 6.0.6 on 2026-07-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='board_type',
            field=models.CharField(choices=[('notice', '공지 사항'), ('qna', '질문 답변'), ('free', '자유 게시판'), ('info', '정보 공유')], max_length=10),
        ),
    ]
