apiVersion: v1
kind: Secret
metadata:
  name: aniverse-app-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aniverse.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets | nindent 2 }}
