apiVersion: v1
kind: Service
metadata:
  name: aniverse-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aniverse.labels" . | nindent 4 }}
spec:
  selector:
    app: aniverse-web
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
  type: ClusterIP
