# Generated by Django 6.0.6 on 2026-07-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('image_url', models.URLField()),
                ('score', models.FloatField()),
            ],
        ),
    ]
