# Generated by Django 6.0.6 on 2026-07-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='backdrop_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='first_air_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='original_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
