name: Django CD Pipeline (CodeDeploy)

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}  # 또는 vars.S3_BUCKET_NAME
  CODE_DEPLOY_APP_NAME: aniverse-app
  CODE_DEPLOY_GROUP_NAME: aniverse-dg

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 1. 저장소 코드 가져오기
      uses: actions/checkout@v4  # v3에서 v4로 변경

    - name: 2. AWS 인증 정보 설정
      uses: aws-actions/configure-aws-credentials@v4  # v2에서 v4로 변경 (필수!)
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: 3. 프로젝트 파일 압축
      run: zip -r deploy.zip . -x "*.git*"

    - name: 4. 압축 파일을 S3에 업로드
      run: aws s3 cp deploy.zip s3://$S3_BUCKET_NAME/deploy.zip

    - name: 5. CodeDeploy 배포 지시
      run: |
        aws deploy create-deployment \
          --application-name ${{ env.CODE_DEPLOY_APP_NAME }} \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name ${{ env.CODE_DEPLOY_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=deploy.zip
