# Generated by Django 6.0.6 on 2026-07-10 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_program', models.CharField(help_text='예: 귀멸의 칼날, 롤 등', max_length=100, verbose_name='원작 작품명')),
                ('category', models.CharField(choices=[('cosplay', '코스프레'), ('illustration', '일러스트'), ('novel', '소설')], max_length=20, verbose_name='분야')),
                ('title', models.CharField(max_length=200, verbose_name='창작물 제목')),
                ('content', models.TextField(verbose_name='내용 / 소설 본문')),
                ('image', models.ImageField(blank=True, null=True, upload_to='works_images/', verbose_name='창작물 이미지')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_works', to=settings.AUTH_USER_MODEL, verbose_name='크리에이터')),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='bookmarked_works', to=settings.AUTH_USER_MODEL, verbose_name='북마크(보관)')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_works', to=settings.AUTH_USER_MODEL, verbose_name='좋아요(추천)')),
            ],
        ),
    ]
