# Generated by Django 6.0.6 on 2026-07-14 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='works_images/', verbose_name='추가 이미지')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='works.creativework', verbose_name='소속 창작물')),
            ],
        ),
    ]
