# Generated by Django 6.0.6 on 2026-07-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_workimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativework',
            name='status',
            field=models.CharField(choices=[('draft', '임시저장'), ('published', '게시됨')], default='published', max_length=10, verbose_name='상태'),
        ),
    ]
