# Generated by Django 6.0.6 on 2026-07-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_creativework_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativework',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='공개 여부'),
        ),
    ]
